version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: deals-backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: deals-frontend
    command: npm run dev
    depends_on:
      - backend